import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import {ColorSchemeScript, createTheme, MantineColorsTuple, MantineProvider} from "@mantine/core";
import PageHeader from "../components/PageHeader";
import PageFooter from "../components/PageFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Gutenberg",
  description: "Generated by create next app",
};

const oldRose: MantineColorsTuple = [
  "#fff0e9",
  "#f4e3db",
  "#e0c5ba",
  "#cda696",
  "#bd8c78",
  "#b37b64",
  "#af7259",
  "#9a6049",
  "#8a553f",
  "#7a4732"
];

const theme = createTheme({
  primaryColor: "oldRose",
  colors: {
    oldRose,
  }
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link crossOrigin="" rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Poppins:wght@400;700&display=swap" rel="stylesheet" />
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <PageHeader />
          {children}
          <PageFooter />
        </MantineProvider>
      </body>
    </html>
  );
}
