import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import PageHeader from "../components/PageHeader.tsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Gutenberg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet" />
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider>
          <PageHeader />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
